language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
script:
  - yarn run test
  - yarn run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: '79e9ced3efa22ce69a8439e0da6cea45a2e219d7'
  local_dir: build
  on:
    branch: master
